apiVersion: route.openshift.io/v1
kind: Route
metadata:
  {{- if .Values.sename}}
  name: {{lower .Values.name}}-{{lower .Values.sename}}
  {{- else }}
  name: {{lower .Values.name}}
  {{- end }}
  labels:
    {{- if .Values.sename}}
    app: {{lower .Values.name}}-{{lower .Values.sename}}
    {{- else }}
    app: {{lower .Values.name}}
    {{- end }}
spec:
  {{- if .Values.host}}
  host: {{.Values.host}}
  {{- end}}
  port:
    targetPort: {{.Values.serviceTargetPort}}
  tls:
    termination: edge
  to:
    kind: Service
    {{- if .Values.sename}}
    name: {{lower .Values.name}}-{{lower .Values.sename}}
    {{- else }}
    name: {{lower .Values.name}}
    {{- end }}
    weight: 100
